<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.24.84" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnZwDev.System.Logging\AnZwDev.System.Logging.csproj" />
    <ProjectReference Include="..\AnZwDev.System.ServiceModel\AnZwDev.System.ServiceModel.csproj" />
    <ProjectReference Include="..\AnZwDev.System\AnZwDev.System.csproj" />
  </ItemGroup>

</Project>
