using System;
using System.Collections.Generic;
using System.Text;

namespace AnZwDev.ALTools.ALSymbols.Internal
{
    public enum ConvertedSymbolKind
    {
        Undefined = -1,
        Module = 0,
        ErrorType = 1,
        NamedType = 2,
        ArrayType = 3,
        Label = 4,
        Class = 9,
        Table = 10,
        Codeunit = 11,
        Page = 12,
        Report = 13,
        Query = 14,
        XmlPort = 15,
        PageExtension = 16,
        TableExtension = 17,
        Profile = 18,
        ControlAddIn = 19,
        DotNetTypeDeclaration = 20,
        PageCustomization = 21,
        Enum = 22,
        EnumExtension = 23,
        ProfileExtension = 24,
        Interface = 25,
        PermissionSet = 26,
        ReportExtension = 27,
        PermissionSetExtension = 28,
        Entitlement = 29,
        GlobalVariable = 40,
        Method = 41,
        Event = 42,
        LocalVariable = 43,
        Parameter = 44,
        ReturnValue = 45,
        Field = 50,
        Option = 51,
        Property = 52,
        PropertyValue = 53,
        Attribute = 54,
        AttributeArgument = 55,
        Key = 56,
        FieldGroup = 57,
        OptionType = 58,
        Control = 60,
        Action = 61,
        EnumValue = 62,
        View = 63,
        Permission = 64,
        TestPage = 70,
        TestField = 71,
        TestAction = 72,
        TestRequestPage = 73,
        TestPart = 75,
        TestFilter = 76,
        TestFilterField = 77,
        Change = 80,
        Record = 90,
        PageReference = 91,
        QueryDataItem = 100,
        QueryFilter = 101,
        QueryColumn = 102,
        ReportDataItem = 103,
        ReportColumn = 104,
        ReportLabel = 105,
        RequestPage = 106,
        ReportReference = 107,
        XmlPortNode = 109,
        XmlPortReference = 110,
        QueryReference = 111,
        DotNetAssembly = 112,
        DotNetPackage = 113,
        DotNet = 114,
        RequestPageExtension = 115
    }
}
