<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnZwDev.AL.Symbols.Formatters\AnZwDev.AL.Symbols.Formatters.csproj" />
    <ProjectReference Include="..\AnZwDev.AL.Symbols.Providers.AppPackages\AnZwDev.AL.Symbols.Providers.AppPackages.csproj" />
    <ProjectReference Include="..\AnZwDev.AL.Symbols\AnZwDev.AL.Symbols.csproj" />
    <ProjectReference Include="..\AnZwDev.AL.Workspaces\AnZwDev.AL.Workspaces.csproj" />
    <ProjectReference Include="..\AnZwDev.LanguageServer\AnZwDev.LanguageServer.csproj" />
    <ProjectReference Include="..\AnZwDev.System.Collections\AnZwDev.System.Collections.csproj" />
    <ProjectReference Include="..\AnZwDev.System.IO\AnZwDev.System.IO.csproj" />
    <ProjectReference Include="..\AnZwDev.System.Logging\AnZwDev.System.Logging.csproj" />
    <ProjectReference Include="..\AnZwDev.System.ServiceModel\AnZwDev.System.ServiceModel.csproj" />
    <ProjectReference Include="..\AnZwDev.System\AnZwDev.System.csproj" />
  </ItemGroup>

</Project>
