<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnZwDev.AL.LanguageServer.Modules.SymbolsSourceProvider\AnZwDev.AL.LanguageServer.Modules.SymbolsSourceProvider.csproj" />
    <ProjectReference Include="..\AnZwDev.AL.Workspaces.Documents.SymbolsViewers\AnZwDev.AL.Workspaces.Documents.SymbolsViewers.csproj" />
    <ProjectReference Include="..\AnZwDev.AL.Workspaces\AnZwDev.AL.Workspaces.csproj" />
    <ProjectReference Include="..\AnZwDev.LanguageServer\AnZwDev.LanguageServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
