name: Build Extension
run-name: Build Extension
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
            
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup VSCode extensions libraries
        run: npm install -g @vscode/vsce

      - name: Setup .NET Core SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore dependencies
        run: |
          cd "language-server"
          nuget restore AZALDevToolsServer.sln
          cd "..\vscode-extension"
          npm install
          cd ".."
     
      - name: Build VS Code extension
        run: .\build.ps1 -PreRelease $false

      - name: Upload VS Code extension to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "vscode-extension/*.vsix"